// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBECM3XwqHUUWfFYdiBO7BWVk7d3HEkuM0',
    appId: '1:680216710528:web:18bf5c149b70c3083b0565',
    messagingSenderId: '680216710528',
    projectId: 'my-finance-with-login',
    authDomain: 'my-finance-with-login.firebaseapp.com',
    storageBucket: 'my-finance-with-login.firebasestorage.app',
    measurementId: 'G-205JCL0RCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_8sn_aAyEy19s5NsC-mOqF3XhmcYTpZQ',
    appId: '1:680216710528:android:1b0bd65ac6e541d63b0565',
    messagingSenderId: '680216710528',
    projectId: 'my-finance-with-login',
    storageBucket: 'my-finance-with-login.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4uUVyVtPEpj2H3foGSwcJjZ9aY3yh5YE',
    appId: '1:680216710528:ios:03d491a0f6d9a96d3b0565',
    messagingSenderId: '680216710528',
    projectId: 'my-finance-with-login',
    storageBucket: 'my-finance-with-login.firebasestorage.app',
    iosBundleId: 'com.example.myFinances',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4uUVyVtPEpj2H3foGSwcJjZ9aY3yh5YE',
    appId: '1:680216710528:ios:03d491a0f6d9a96d3b0565',
    messagingSenderId: '680216710528',
    projectId: 'my-finance-with-login',
    storageBucket: 'my-finance-with-login.firebasestorage.app',
    iosBundleId: 'com.example.myFinances',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBECM3XwqHUUWfFYdiBO7BWVk7d3HEkuM0',
    appId: '1:680216710528:web:5c7375c63b550f8a3b0565',
    messagingSenderId: '680216710528',
    projectId: 'my-finance-with-login',
    authDomain: 'my-finance-with-login.firebaseapp.com',
    storageBucket: 'my-finance-with-login.firebasestorage.app',
    measurementId: 'G-Q3P87RMMS0',
  );

}